language: java
sudo: required
cache: 
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
install:
  - cd desapp-groupe-backend 
  - mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
deploy:
  - provider: heroku
    skip_cleanup: true
    api_key: 6813f888-06ed-4f94-88c0-8653484eec5d
    app: desapp-unq-groupe-backend
